# Generated by Django 3.2 on 2022-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_federation_agent',
            field=models.BooleanField(default=False, verbose_name='Is federation agent?'),
        ),
    ]
