# Generated by Django 3.2 on 2022-07-08 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumSeatPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('stadium_seat_id', models.IntegerField(verbose_name='Stadium seat ID')),
                ('status', models.IntegerField(choices=[(0, 'Healthy'), (1, 'Broken'), (2, 'Repair')], default=0, verbose_name='Status')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_places', to='federation.stadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Stadium seat place',
                'verbose_name_plural': 'Stadium seat places',
                'unique_together': {('stadium_seat_id', 'stadium')},
            },
        ),
    ]
